services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./frontend:/app

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nikolas1234
      POSTGRES_DB: exchangehub
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
